name: Setup environment

runs:
  using: "composite"
  steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.78.0
        override: true
        components: rustfmt, clippy
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.4.0
        run_install: false
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "pnpm"
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
    - name: Install Solana
      uses: metaplex-foundation/actions/install-solana@v1
      with:
        version: 1.18.15
        cache: "true"
