[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
puppet = "6nxvjh3D3kLkkb25sgRUdyomfYqeoUv7gfRFgcScy6jN"

[registry]
url = "https://api.apr.dev"
# url = "http://127.0.0.1:8899"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

# [[test.validator.clone]]
# address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
