[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
puppet = "6nxvjh3D3kLkkb25sgRUdyomfYqeoUv7gfRFgcScy6jN"

[programs.devnet]
puppet = "6nxvjh3D3kLkkb25sgRUdyomfYqeoUv7gfRFgcScy6jN"

[programs.mainnet]
puppet = "6nxvjh3D3kLkkb25sgRUdyomfYqeoUv7gfRFgcScy6jN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[[test.genesis]]
address = "hdMghjD73uASxgJXi6e1mGPsXqnADMsrqB1bveqABP1"
program = "../../target/deploy/dephy_id_program.so"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/fixtures/mpl_token_metadata.so"

[scripts]
test = "bun run -b test"
