// GENERATED by @edgedb/generate v0.5.3

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
export type $KeyType = {
  "Ed25519": $.$expr_Literal<$KeyType>;
  "Secp256k1": $.$expr_Literal<$KeyType>;
} & $.EnumType<"default::KeyType", ["Ed25519", "Secp256k1"]>;
const KeyType: $KeyType = $.makeType<$KeyType>(_.spec, "84f9d314-1764-11ef-83b1-0f5c0af2a7ed", _.syntax.literal);

export type $SolanaAccountλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "pubkey": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
}>;
type $SolanaAccount = $.ObjectType<"default::SolanaAccount", $SolanaAccountλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {pubkey: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $SolanaAccount = $.makeType<$SolanaAccount>(_.spec, "84f08cd2-1764-11ef-9237-db8d98ac5739", _.syntax.literal);

const SolanaAccount: $.$expr_PathNode<$.TypeSet<$SolanaAccount, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SolanaAccount, $.Cardinality.Many), null);

export type $AdminλShape = $.typeutil.flatten<$SolanaAccountλShape & {
  "<authority[is DePHY]": $.LinkDesc<$DePHY, $.Cardinality.Many, {}, false, false,  false, false>;
  "<authority": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Admin = $.ObjectType<"default::Admin", $AdminλShape, null, [
  ...$SolanaAccount['__exclusives__'],
]>;
const $Admin = $.makeType<$Admin>(_.spec, "84f178e0-1764-11ef-9c63-11928b3c718e", _.syntax.literal);

const Admin: $.$expr_PathNode<$.TypeSet<$Admin, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Admin, $.Cardinality.Many), null);

export type $SplMintλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "metadata": $.LinkDesc<$TokenMetadata, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "mint_account": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
  "mint_authority": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
}>;
type $SplMint = $.ObjectType<"default::SplMint", $SplMintλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {mint_account: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $SplMint = $.makeType<$SplMint>(_.spec, "84f6d33a-1764-11ef-9c5f-a7a5d5e09a2e", _.syntax.literal);

const SplMint: $.$expr_PathNode<$.TypeSet<$SplMint, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SplMint, $.Cardinality.Many), null);

export type $SplAccountλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "token_account": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, true, false, false, false>;
}>;
type $SplAccount = $.ObjectType<"default::SplAccount", $SplAccountλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {token_account: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $SplAccount = $.makeType<$SplAccount>(_.spec, "84f5ec54-1764-11ef-a34d-a7106ecd76c7", _.syntax.literal);

const SplAccount: $.$expr_PathNode<$.TypeSet<$SplAccount, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SplAccount, $.Cardinality.Many), null);

export type $WithIxλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "tx": $.LinkDesc<$Transaction, $.Cardinality.One, {
    "@ix_index": $.PropertyDesc<_std.$int16, $.Cardinality.AtMostOne>;
  }, false, false, false, false>;
}>;
type $WithIx = $.ObjectType<"default::WithIx", $WithIxλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $WithIx = $.makeType<$WithIx>(_.spec, "84f3b330-1764-11ef-ac2c-6b13f1d1b9e9", _.syntax.literal);

const WithIx: $.$expr_PathNode<$.TypeSet<$WithIx, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($WithIx, $.Cardinality.Many), null);

export type $DIDλShape = $.typeutil.flatten<$SplMintλShape & $SplAccountλShape & $WithIxλShape & {
  "device": $.LinkDesc<$Device, $.Cardinality.One, {}, true, false,  false, false>;
  "user": $.LinkDesc<$User, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "<did[is Device]": $.LinkDesc<$Device, $.Cardinality.Many, {}, false, false,  false, false>;
  "<dids[is User]": $.LinkDesc<$User, $.Cardinality.Many, {}, false, false,  false, false>;
  "<did": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<dids": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $DID = $.ObjectType<"default::DID", $DIDλShape, null, [
  ...$SplMint['__exclusives__'],
  ...$SplAccount['__exclusives__'],
  ...$WithIx['__exclusives__'],
  {device: {__element__: $Device, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $DID = $.makeType<$DID>(_.spec, "84f7fd1e-1764-11ef-9f61-cb1d3c250d67", _.syntax.literal);

const DID: $.$expr_PathNode<$.TypeSet<$DID, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($DID, $.Cardinality.Many), null);

export type $DePHYλShape = $.typeutil.flatten<$SolanaAccountλShape & $WithIxλShape & {
  "authority": $.LinkDesc<$Admin, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $DePHY = $.ObjectType<"default::DePHY", $DePHYλShape, null, [
  ...$SolanaAccount['__exclusives__'],
  ...$WithIx['__exclusives__'],
]>;
const $DePHY = $.makeType<$DePHY>(_.spec, "84f484fe-1764-11ef-836c-8f7b18b7da19", _.syntax.literal);

const DePHY: $.$expr_PathNode<$.TypeSet<$DePHY, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($DePHY, $.Cardinality.Many), null);

export type $DeviceλShape = $.typeutil.flatten<$SolanaAccountλShape & Omit<$SplAccountλShape, "token_account"> & $WithIxλShape & {
  "key_type": $.PropertyDesc<$KeyType, $.Cardinality.One, false, false, false, false>;
  "token_account": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
  "did": $.LinkDesc<$DID, $.Cardinality.AtMostOne, {}, false, true,  false, false>;
  "product": $.LinkDesc<$Product, $.Cardinality.One, {}, false, false,  false, false>;
  "<device[is DID]": $.LinkDesc<$DID, $.Cardinality.AtMostOne, {}, true, false,  false, false>;
  "<devices[is Product]": $.LinkDesc<$Product, $.Cardinality.Many, {}, false, false,  false, false>;
  "<device": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<devices": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Device = $.ObjectType<"default::Device", $DeviceλShape, null, [
  ...$SolanaAccount['__exclusives__'],
  ...$SplAccount['__exclusives__'],
  ...$WithIx['__exclusives__'],
  {token_account: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $Device = $.makeType<$Device>(_.spec, "84f9dd28-1764-11ef-b371-4df87ba950b8", _.syntax.literal);

const Device: $.$expr_PathNode<$.TypeSet<$Device, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Device, $.Cardinality.Many), null);

export type $ProductλShape = $.typeutil.flatten<$SplMintλShape & $WithIxλShape & {
  "devices": $.LinkDesc<$Device, $.Cardinality.Many, {}, false, true,  false, false>;
  "vendor": $.LinkDesc<$Vendor, $.Cardinality.One, {}, false, false,  false, false>;
  "<product[is Device]": $.LinkDesc<$Device, $.Cardinality.Many, {}, false, false,  false, false>;
  "<products[is Vendor]": $.LinkDesc<$Vendor, $.Cardinality.Many, {}, false, false,  false, false>;
  "<product": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<products": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Product = $.ObjectType<"default::Product", $ProductλShape, null, [
  ...$SplMint['__exclusives__'],
  ...$WithIx['__exclusives__'],
]>;
const $Product = $.makeType<$Product>(_.spec, "84fe76ee-1764-11ef-bcd6-4d3ed8e4de34", _.syntax.literal);

const Product: $.$expr_PathNode<$.TypeSet<$Product, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Product, $.Cardinality.Many), null);

export type $TokenMetadataλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "additional": $.PropertyDesc<$.ArrayType<$.TupleType<[_std.$str, _std.$str]>>, $.Cardinality.One, false, false, false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "symbol": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "uri": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "<metadata[is SplMint]": $.LinkDesc<$SplMint, $.Cardinality.Many, {}, false, false,  false, false>;
  "<metadata[is DID]": $.LinkDesc<$DID, $.Cardinality.Many, {}, false, false,  false, false>;
  "<metadata[is Product]": $.LinkDesc<$Product, $.Cardinality.Many, {}, false, false,  false, false>;
  "<metadata[is Vendor]": $.LinkDesc<$Vendor, $.Cardinality.Many, {}, false, false,  false, false>;
  "<metadata": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $TokenMetadata = $.ObjectType<"default::TokenMetadata", $TokenMetadataλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $TokenMetadata = $.makeType<$TokenMetadata>(_.spec, "84ef9e08-1764-11ef-be62-31acc43aaa4a", _.syntax.literal);

const TokenMetadata: $.$expr_PathNode<$.TypeSet<$TokenMetadata, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($TokenMetadata, $.Cardinality.Many), null);

export type $TransactionλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "block_ts": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
  "err": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "processed": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, true>;
  "signature": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
  "slot": $.PropertyDesc<_std.$bigint, $.Cardinality.One, false, false, false, false>;
  "<tx[is WithIx]": $.LinkDesc<$WithIx, $.Cardinality.Many, {}, false, false,  false, false>;
  "<tx[is DePHY]": $.LinkDesc<$DePHY, $.Cardinality.Many, {}, false, false,  false, false>;
  "<tx[is DID]": $.LinkDesc<$DID, $.Cardinality.Many, {}, false, false,  false, false>;
  "<tx[is Device]": $.LinkDesc<$Device, $.Cardinality.Many, {}, false, false,  false, false>;
  "<tx[is Product]": $.LinkDesc<$Product, $.Cardinality.Many, {}, false, false,  false, false>;
  "<tx[is Vendor]": $.LinkDesc<$Vendor, $.Cardinality.Many, {}, false, false,  false, false>;
  "<tx": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Transaction = $.ObjectType<"default::Transaction", $TransactionλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {signature: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $Transaction = $.makeType<$Transaction>(_.spec, "84f2790c-1764-11ef-8c08-e5b2c91b81e0", _.syntax.literal);

const Transaction: $.$expr_PathNode<$.TypeSet<$Transaction, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Transaction, $.Cardinality.Many), null);

export type $UserλShape = $.typeutil.flatten<$SolanaAccountλShape & {
  "dids": $.LinkDesc<$DID, $.Cardinality.Many, {}, false, true,  false, false>;
  "<user[is DID]": $.LinkDesc<$DID, $.Cardinality.Many, {}, false, false,  false, false>;
  "<user": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $User = $.ObjectType<"default::User", $UserλShape, null, [
  ...$SolanaAccount['__exclusives__'],
]>;
const $User = $.makeType<$User>(_.spec, "84fcae4a-1764-11ef-a882-439ed14237a4", _.syntax.literal);

const User: $.$expr_PathNode<$.TypeSet<$User, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($User, $.Cardinality.Many), null);

export type $VendorλShape = $.typeutil.flatten<$SolanaAccountλShape & $SplMintλShape & Omit<$SplAccountλShape, "token_account"> & $WithIxλShape & {
  "token_account": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
  "products": $.LinkDesc<$Product, $.Cardinality.Many, {}, false, true,  false, false>;
  "<vendor[is Product]": $.LinkDesc<$Product, $.Cardinality.Many, {}, false, false,  false, false>;
  "<vendor": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Vendor = $.ObjectType<"default::Vendor", $VendorλShape, null, [
  ...$SolanaAccount['__exclusives__'],
  ...$SplMint['__exclusives__'],
  ...$SplAccount['__exclusives__'],
  ...$WithIx['__exclusives__'],
  {token_account: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $Vendor = $.makeType<$Vendor>(_.spec, "8502ecd8-1764-11ef-a2c3-4da18d40de2f", _.syntax.literal);

const Vendor: $.$expr_PathNode<$.TypeSet<$Vendor, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Vendor, $.Cardinality.Many), null);



export { KeyType, $SolanaAccount, SolanaAccount, $Admin, Admin, $SplMint, SplMint, $SplAccount, SplAccount, $WithIx, WithIx, $DID, DID, $DePHY, DePHY, $Device, Device, $Product, Product, $TokenMetadata, TokenMetadata, $Transaction, Transaction, $User, User, $Vendor, Vendor };

type __defaultExports = {
  "KeyType": typeof KeyType;
  "SolanaAccount": typeof SolanaAccount;
  "Admin": typeof Admin;
  "SplMint": typeof SplMint;
  "SplAccount": typeof SplAccount;
  "WithIx": typeof WithIx;
  "DID": typeof DID;
  "DePHY": typeof DePHY;
  "Device": typeof Device;
  "Product": typeof Product;
  "TokenMetadata": typeof TokenMetadata;
  "Transaction": typeof Transaction;
  "User": typeof User;
  "Vendor": typeof Vendor
};
const __defaultExports: __defaultExports = {
  "KeyType": KeyType,
  "SolanaAccount": SolanaAccount,
  "Admin": Admin,
  "SplMint": SplMint,
  "SplAccount": SplAccount,
  "WithIx": WithIx,
  "DID": DID,
  "DePHY": DePHY,
  "Device": Device,
  "Product": Product,
  "TokenMetadata": TokenMetadata,
  "Transaction": Transaction,
  "User": User,
  "Vendor": Vendor
};
export default __defaultExports;
