pub const PROGRAM_PDA_SEED_PREFIX: &[u8; 8] = b"DePHY_ID";
pub const PRODUCT_MINT_SEED_PREFIX: &[u8; 16] = b"DePHY_ID-PRODUCT";
pub const DEVICE_MINT_SEED_PREFIX: &[u8; 15] = b"DePHY_ID-DEVICE";

pub const DEVICE_MESSAGE_PREFIX: &[u8; 8] = b"DEPHY_ID";
