// GENERATED by @edgedb/generate v0.5.3

import type {Executor} from "edgedb";

export type GetDIDArgs = {
  readonly "did_atoken": string;
};

export type GetDIDReturns = {
  "mint_account": string;
  "token_account": string | null;
  "device": {
    "token_account": string;
    "pubkey": string;
    "product": {
      "mint_account": string;
      "vendor": {
        "pubkey": string;
      };
    };
  };
  "owner": {
    "pubkey": string;
  } | null;
} | null;

export function getDID(client: Executor, args: GetDIDArgs): Promise<GetDIDReturns> {
  return client.querySingle(`\
select default::DID {
  mint_account,
  token_account,
  device: {
    token_account,
    pubkey,
    product: {
      mint_account,
      vendor: {
        pubkey
      }
    }
  },
  owner: {
    pubkey
  }
}
filter .token_account = <str>$did_atoken`, args);

}
