// GENERATED by @edgedb/generate v0.5.3

import type {Executor} from "edgedb";


export type GetDeviceCountReturns = number;

export function getDeviceCount(client: Executor): Promise<GetDeviceCountReturns> {
  return client.queryRequiredSingle(`\
select count(Device);`);

}
