// GENERATED by @edgedb/generate v0.5.3

import type {Executor} from "edgedb";

export type GetVendorArgs = {
  readonly "vendor_pubkey": string;
};

export type GetVendorReturns = {
  "pubkey": string;
  "products": Array<{
    "mint_authority": string | null;
    "mint_account": string;
    "metadata": {
      "name": string | null;
      "symbol": string | null;
      "uri": string;
      "additional": Array<[string, string]>;
    } | null;
    "block_ts": Date | null;
    "device_count": number;
  }>;
} | null;

export function getVendor(client: Executor, args: GetVendorArgs): Promise<GetVendorReturns> {
  return client.querySingle(`\
select default::Vendor {
  pubkey,
  products: {
    mint_authority,
    mint_account,
    metadata: {
      name,
      symbol,
      uri,
      additional
    },
    block_ts := .tx.block_ts,
    device_count := count(.devices)
  }
}
filter .pubkey = <str>$vendor_pubkey`, args);

}
